### ISSUE TITLE
Better categorization

### ISSUE THREAD

**Issue by gdamdam** [gdamdam/awesome-decentralized-web#14]
We need a better categorization

**Comment by johnjago** [comment]
I agree. Many of the categories overlap, and a lot is thrown into the miscellaneous section.

Starting at a high level, it might be good to separate protocols and technologies from applications of those protocols and technologies.

**Comment by gdamdam** [comment]
@johnjago: feel free to submit a pull request with better categories ;)

**Comment by johnjago** [comment]
@gdamdam Are there any specific categories you would like to see?

**Comment by gdamdam** [comment]
we have a better categorization!!! thank you @johnjago
