### ISSUE TITLE
Update broken links and project names

### ISSUE THREAD

**Issue by johnjago** [gdamdam/awesome-decentralized-web#17]
Several of the links are broken, and a couple projects have changed their names. Here is what I have found so far:

- ORC (https://orc.network) is down
- WikipediaP2P is now at https://guerrerocarlos.github.io/WikiP2P.org/
- trsst domain is no longer active (could use https://github.com/TrsstProject/trsst)
- ferment is now at https://github.com/fermentation/ferment
- git-ssb has been archived
- GitPub is now ForgeFed (https://github.com/forgefed/forgefed)
- Onename is now a domain registrar for Blockstack and the description should be updated

**Comment by gdamdam** [comment]
thank you!!
changes in the commit: https://github.com/gdamdam/awesome-decentralized-web/commit/c4384ee783f9006f4db6cfec1fe388b8a5957a0a
