### ISSUE TITLE
Tag discontinued project

### ISSUE THREAD

**Issue by linsui** [gdamdam/awesome-decentralized-web#22]
Some projects have been unmaintained for over one year. Could you please tag them as discontinued? For example,  latest commit of WikiP2P was on 6 Feb 2017.

**Comment by gdamdam** [comment]
cool, 
feel free to submit a pull request with the updates about the discontinued projects, I will be happy to approve it.

**Comment by linsui** [comment]
OK, I'll do it soon. :ok:

**Comment by gdamdam** [comment]
merged
