### ISSUE TITLE
zeronet is not based on bitcoin blockchain, but bitcoin crypto

### ISSUE THREAD

**Issue by blurHY** [gdamdam/awesome-decentralized-web#30]

**Comment by gdamdam** [comment]
zeronet use bitcoin blockchain.
Crypto means cryptography.

**Comment by blurHY** [comment]
> zeronet use bitcoin blockchain.

Absolutely wrong

> Crypto means cryptography.

 I know.
It's based on bitcoin asymmetric crypto

**Comment by gdamdam** [comment]
oh I understand what you mean.
I've changes it in "bitcoin cryptography"
thank you @blurHY
