### ISSUE TITLE
Add Send and ffsend

### ISSUE THREAD

**Issue by timvisee** [gdamdam/awesome-decentralized-web#42]
Here's a suggestion for 'Data Storage and Sharing'. I'm not sure if it fits the list, which is why I'm opening an issue instead of a pull request.

My suggestion is [Send](https://github.com/timvisee/send). It allows E2E encrypted file sharing with temporary uploads. It was originally developed by Mozilla named [Firefox Send](https://github.com/mozilla/send), but they discontinued it. I'm maintaining a popular for for it.

In addition to that [`ffsend`](https://github.com/timvisee/ffsend) may be useful for it as command-line client for Send.

Is this something that can be added? I'd be happy to submit a PR.

**Comment by leonstafford** [comment]
@timvisee looks awesome, great work!

Not sure if [the usage of your own public box](https://gitlab.com/timvisee/ffsend/-/issues/101) may not meet the "Decentralized/Distributed" aspect of this list?

**Comment by timvisee** [comment]
> Not sure if [the usage of your own public box](https://gitlab.com/timvisee/ffsend/-/issues/101) meets the "Decentralized/Distributed" aspect of this list?

No. That's why I meant to list it as self hostable project instead of a hosted platform.

**Comment by gdamdam** [comment]
Thank you for the suggestion, but this list is about decentralized/distributed services and  Send is not fitting the requirements

**Comment by timvisee** [comment]
> Thank you for the suggestion, but this list is about decentralized/distributed services and Send is not fitting the requirements

Thanks for looking into it. This is why I opened an issue. I understand.
