### ISSUE TITLE
Hypercore protocol

### ISSUE THREAD

**Issue by mdelbuono** [gdamdam/awesome-decentralized-web#45]
In README.md, under the *Data* section, you mention the Dat protocol. 

It looks like that project is kept alive only for legacy reasons, while the development has moved to the [hypercore protocol](https://hypercore-protocol.org/).

See [this video](https://youtu.be/mx52uO5SP7A).

**Comment by gdamdam** [comment]
cool thank you! please submit a Pull Request so I will update the list with you in the contributors.

**Comment by gdamdam** [comment]
merget with https://github.com/gdamdam/awesome-decentralized-web/pull/46
