### ISSUE TITLE
WebRTC isn't decentralized in most cases

### ISSUE THREAD

**Issue by Atavic** [gdamdam/awesome-decentralized-web#7]
WebRTC by default uses STUN servers, see [here](https://www.html5rocks.com/en/tutorials/webrtc/basics/#stun) for an explanation.

**Comment by gdamdam** [comment]
This is true: WebRTC is not decentralized in most cases.
We added this technology because its p2p use and potential.

**Comment by Atavic** [comment]
:+1: that's fair.
